Sprint2/step2
alexxxwork/react-burger pull request #4
Opened 2022-11-17 02:10 UTC by alexxxwork

2022-11-17 03:50 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

-   Декомпозиция файлов по директориям - практически соответствует описанию;
-   Сборка и запуск проекта выполняются без ошибок;
-   Используются функциональные компоненты;
-   Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

-   В компоненте App-header требуется поправить семантику, нужно обернуть иконку и текст в ссылку.

-   По макету, в app-header, должна быть активна только первая ссылка.

-   Там где содержится `jsx`, лучше заменить расширения с `.js` на `.jsx`.

-   Старайтесь не отключать линтер, он в большей степени помогает вам, а не ограничивает.

-   Лучше ограничть отправку запроса `/order`, если есть только булки, но нет ингредментов.

-   Количество булок должно быть 2 штуки. https://yadi.sk/d/98zC_W3o2iDdWA

-   Разделите reducers и actions, по файлам.

### **Сделает код лучше:**

-   Лучше расположить элементы по центру: https://yadi.sk/d/6my-YPdnGZUpkQ;

-   Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

-   Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/app/app.js
>      const [state, setState] = React.useState({
**Надо исправить:** 

Вы уже используете redux, поэтому этот стейт нужно убрать, чтобы не было дублирования.

Также нужно убрать `useEffect`, запросы дублируются.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
>      let bottom = {};
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
>      let top = {};
**Надо исправить:**

Здесь и далее.

Если данных нет, то следует записывать null а не пустой объект.


**Можно лучше:** 

Присваивание (ниже), лучше вынести в отдельную функцию, чтобы не смотрелось так громоздко.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
>                          .filter((i) => i.type !== BUN_NAME)
**Можно лучше:** 

Фильтрацию лучше делать до `jsx`

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
>      function reducer() {
**Можно лучше:**

Сейчас вы используйте redux, поэтому логика должна быть там, тут не стоит использовать контекст. 
Да и тем более для подсчёта суммы не нужно использовать никакой state менеджер. Просто сделайте это через useMemo.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.js
> +    const refs = { buns: useRef(), main: useRef(), sauce: useRef() };
**Надо исправить:** 

Тут лучше использовать useMemo, и старайтесь не отключать линтер, он в большей степени помогает вам, а не ограничивает.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/order.js
> +    data: {},
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/order.js
> +export const orderReducer = createReducer(initialState, (builder) => {
**Надо исправить:**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers


В вашем случае это слайсы, но думаю вы поняли мысль.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +            .then(async (res) => {
**Можно лучше:** А почему бы тут не использовать `checkResponse` ?

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +                              bun._id,
**Надо исправить:** Булка должна быть в начале и в конце массива.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +export const initialState = {
**Надо исправить:** 

Лучше вынести в нужный редьюсер. Тоже самое касается и функций ниже, они должны находиться рядом с нужным редьюсером.

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/reducers/items.js
> +            else state.ingredients.push({ ...action.payload, id: uuid() });
**Надо исправить:** редьюсеры должны быть чистыми функциями, чтобы присвоить уникальный id используйте кастомный action-creator: https://redux-toolkit.js.org/api/createslice#customizing-generated-action-creators

2022-11-17 03:50 UTC, ArslanDev666 commented on src/services/actions/index.js
> +import { createAction } from '@reduxjs/toolkit';
**Надо исправить:**

следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2022-11-17 06:19 UTC, alexxxwork commented on src/components/burger-ingredients/burger-ingredients.js
> +    const refs = { buns: useRef(), main: useRef(), sauce: useRef() };
А как тут использовать useMemo? Я пробовал, useRef внутри useMemo не работает

2022-11-17 06:21 UTC, alexxxwork commented on src/services/reducers/order.js
> +export const orderReducer = createReducer(initialState, (builder) => {
itemsReducer нужно поделить? в order делить особо нечего, только на слайсы переписать

2022-11-17 06:28 UTC, alexxxwork commented on src/services/reducers/index.js
> +            .then(async (res) => {
Что за checkResponse?

2022-11-20 21:24 UTC, alexxxwork commented on src/components/burger-ingredients/burger-ingredients.js
> +    const refs = { buns: useRef(), main: useRef(), sauce: useRef() };
Тут не нужно useMemo, переписал по-другому

2022-11-21 03:52 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.js
> +    const refs = { buns: useRef(), main: useRef(), sauce: useRef() };
Да действительно не нужен, что-то я напутал))

2022-11-21 03:55 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +            .then(async (res) => {
Проверка запроса от сервера)) почему-то думал что у вас уже есть эта функция)) 
```
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

Её лучше положить в  файлик `utils/api.js`.

2022-11-23 04:55 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +    devTools: true,
**Можно лучше:**

Лучше сделать проверку на продакш, с помощью `env` переменных)

2022-11-23 04:58 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа 🔥

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2022-11-23 04:58 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +    devTools: true,
**Можно лучше:**

Лучше сделать проверку на продакш, с помощью `env` переменных)

2022-12-11 19:29 UTC, alexxxwork commented on src/components/burger-constructor/burger-constructor.js
>      function reducer() {
Что-то не понимаю, к чему этот коммент. Выделены строки про hover

2022-12-11 19:43 UTC, merged